---
deployment:
  tasks:
    - export FRONTEND_PUBLIC_PATH="/home/cetmedcl/new.cetmed.cl"
    - export REPO_PATH="/home/cetmedcl/repositories/cetmed"
    - /bin/test -d $REPO_PATH/frontend/dist
    - /bin/rsync -av --delete --exclude='config.js' $REPO_PATH/frontend/dist/ $FRONTEND_PUBLIC_PATH/
